### PR TITLE
Adding release script for Cloud Foundry compatibility.

### PR DESCRIPTION
**Pull request by cwest**
Thanks for this great buildpack!

This pull request provides compatibility with [Cloud Foundry](http://cloudfoundry.org) by implementing the required `bin/release` script. See [the docs](http://docs.cloudfoundry.org/buildpacks/custom.html#release-script) for more info on that.

With this change I've successfully pushed an [example app](https://github.com/cwest/cfenv-rust) to a Cloud Foundry instance.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Hey! Thanks so much! I'll merge this definitely. Do you think you could add a bit to the README for people interested?

Currently the build is failing because of `rand` being broken.

**Comment by cwest** [comment]
@Hoverbear I'll update the README as well. Expect an update to this PR in a couple days.

**Comment by Hoverbear** [comment]
Thanks a lot!

**Comment by Hoverbear** [comment]
@cwest Would you like me to merge this and take a separate PR for the README?

**Comment by Hoverbear** [comment]
Closed due to inactivity.

**Pull request closed without merging**
